<a href="https://colab.research.google.com/github/hanocha/try-tensorflow/blob/master/simple_nn_with_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np

mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape([60000, -1])
X_test = X_test.reshape([10000, -1])

print(X_train.shape)
print(X_test.shape)

mean_vals = np.mean(X_train, axis=0)
std_val = np.std(X_train)

X_train_centered = (X_train - mean_vals) / std_val
X_test_centered = (X_test - mean_vals) / std_val

print(X_train_centered.shape, y_train.shape)
print(X_test_centered.shape, y_test.shape)

print(y_train)

11493376/11490434 [==============================] - 0s 0us/step
(60000, 784)
(10000, 784)
(60000, 784) (60000,)
(10000, 784) (10000,)
[5 0 4 ... 5 6 8]


In [0]:
from tensorflow import keras

np.random.seed(12)
tf.set_random_seed(123)

y_train_onehot = keras.utils.to_categorical(y_train)
print(y_train[:3])

[5 0 4]


In [0]:
model = keras.models.Sequential()

model.add(
    keras.layers.Dense(
        units=50,
        input_dim=X_train_centered.shape[1],
        kernel_initializer='glorot_uniform',
        bias_initializer='zeros',
        activation='tanh',
    )
)

model.add(
    keras.layers.Dense(
        units=50,
        input_dim=50,
        kernel_initializer='glorot_uniform',
        bias_initializer='zeros',
        activation='tanh',
    )   
)

model.add(
    keras.layers.Dense(
        units=y_train_onehot.shape[1],
        input_dim=50,
        kernel_initializer='glorot_uniform',
        bias_initializer='zeros',
        activation='softmax',
    )
)

sgd_optimizer = keras.optimizers.SGD(
    lr=0.001,
    decay=1e-7,
    momentum=.9,
)

model.compile(
    optimizer=sgd_optimizer,
    loss='categorical_crossentropy',
)

history = model.fit(
    X_train_centered,
    y_train_onehot,
    batch_size=64,
    epochs=50,
    verbose=1,
    validation_split=0.1,
)

Train on 54000 samples, validate on 6000 samples
Epoch 1/50
54000/54000 [==============================] - 2s 42us/sample - loss: 0.7229 - val_loss: 0.3539
Epoch 2/50
54000/54000 [==============================] - 2s 33us/sample - loss: 0.3630 - val_loss: 0.2659
Epoch 3/50
54000/54000 [==============================] - 2s 32us/sample - loss: 0.2974 - val_loss: 0.2292
Epoch 4/50
54000/54000 [==============================] - 2s 31us/sample - loss: 0.2612 - val_loss: 0.2075
Epoch 5/50
54000/54000 [==============================] - 2s 33us/sample - loss: 0.2365 - val_loss: 0.1911
Epoch 6/50
54000/54000 [==============================] - 2s 33us/sample - loss: 0.2176 - val_loss: 0.1807
Epoch 7/50
54000/54000 [==============================] - 2s 32us/sample - loss: 0.2024 - val_loss: 0.1709
Epoch 8/50
54000/54000 [==============================] - 2s 34us/sample - loss: 0.1898 - val_loss: 0.1633
Epoch 9/50
54000/54000 [==============================] - 2s 33us/sample - loss: 0.1784 - val_l

In [0]:
y_train_pred = model.predict_classes(
    X_train_centered,
    verbose=0,
)

print(y_train_pred[:3])

correnct_preds = np.sum(y_train == y_train_pred, axis = 0)
train_acc = correnct_preds / y_train.shape[0]

print(train_acc)

[5 0 4]
0.9898166666666667


In [0]:
y_test_pred = model.predict_classes(
    X_test_centered,
    verbose=0,
)

print(y_test_pred[:3])

correnct_preds = np.sum(y_test == y_test_pred, axis = 0)
test_acc = correnct_preds /y_test.shape[0]

print(test_acc)

[7 2 1]
0.964
